on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t flask-app .

    - name: Run Docker container
      run: docker run -d --name flask-app flask-app

    - name: Run tests in Docker container
      run: docker exec flask-app python test_ml_api.py
