on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t ml ./machine_learning

    - name: Run Docker container
      run: docker run -d --name mltest ml
    - name: start container
      run: docker start mltest

    - name: Run tests in Docker container
      run: docker exec mltest python tests/test_ml_api.py
